## Types of Analytics
### 1. Descriptive -> past
### 2. Diagnostic -> why
### 3. Predictive -> future
### 4. Prescriptive -> solution

# Numpy (Numerical Python) : Package for Multidimensional Array

In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [ ]:
### Type shift+tab by keeping the mouse in any cell to view the working of method in that cell

In [5]:
list_of_lists = [[1,2,3],[4,5,6],[7,8,9]]
sample_matrix = np.array(list_of_lists)
sample_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(5,20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [7]:
np.arange(18)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [8]:
np.arange(1,46,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41])

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros(5,int)

array([0, 0, 0, 0, 0])

In [11]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
np.ones(100,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [19]:
np.zeros(2,5)

TypeError: Cannot interpret '5' as a data type

In [20]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.zeros((2,5),int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [15]:
### Create an array of zeroes with 2 rows and 10 coulmns
np.zeros((2,10),int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [16]:
### linearly spaced
np.linspace(0,1,5) 

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [17]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [18]:
### Identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
### Uniform distribution of numbers ranging from 0 to 1
np.random.rand(3,2)

array([[0.38804929, 0.16896343],
       [0.92202042, 0.9114042 ],
       [0.750731  , 0.40051064]])

In [8]:
### Normal distribution
np.random.randn(3,2)

array([[-0.64546489,  0.26392692],
       [-1.12296302, -1.12632732],
       [ 0.07362876,  0.3910035 ]])

In [9]:
np.random.randint(34,100)

94

In [10]:
np.random.randint(34,100,50)

array([76, 36, 45, 35, 51, 36, 77, 65, 95, 98, 91, 38, 63, 65, 65, 41, 77,
       50, 55, 48, 72, 81, 77, 64, 93, 74, 98, 66, 67, 41, 92, 89, 69, 46,
       54, 54, 81, 90, 37, 48, 64, 85, 62, 36, 61, 78, 47, 84, 85, 40])

In [11]:
sample_array = np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [12]:
rand_array = np.random.randint(0,100,20)
rand_array

array([97, 30, 83, 75, 35, 67, 93, 70, 95, 60, 65, 71, 68,  7, 20, 12, 13,
       74,  3,  2])

In [18]:
sample_array.reshape(6,5) ### 6*5 = 30

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [19]:
sample_array.reshape(3,10) # 3*10 = 30

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [20]:
sample_array.reshape(4,5) # 4*5 = 20

ValueError: cannot reshape array of size 30 into shape (4,5)

In [14]:
rand_array.min()

2

In [15]:
rand_array.argmin() # argmin means index of the minimum value

19

In [17]:
sample_array.dtype

dtype('int32')

In [21]:
a = np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
a = np.random.rand(3,2)
a

array([[0.12990797, 0.76509387],
       [0.09303687, 0.12596551],
       [0.85664711, 0.17261248]])

In [31]:
a.T

array([[0.12990797, 0.09303687, 0.85664711],
       [0.76509387, 0.12596551, 0.17261248]])

In [23]:
sample_array = np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [26]:
sample_array[3]

13

In [27]:
sample_array[3:7]

array([13, 14, 15, 16])

In [28]:
sample_array[1:4] = 100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [29]:
sample_array = np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [32]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [33]:
subset_sample_array = sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [34]:
subset_sample_array[1:4] = 1001
subset_sample_array

array([  10, 1001, 1001, 1001,   14,   15,   16])

In [35]:
subset_sample_array[:] = 1002
subset_sample_array

array([1002, 1002, 1002, 1002, 1002, 1002, 1002])

## Two Dimensional Array

In [37]:
import numpy as np

In [38]:
sample_matrix = np.array([[50,20,1,23],[24,23,21,33],[56,76,24,7]])
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [39]:
sample_matrix[2][3]

7

In [40]:
sample_matrix[2,:]

array([56, 76, 24,  7])

In [41]:
sample_matrix[2]

array([56, 76, 24,  7])

In [42]:
sample_matrix[:,(3,2)]
# : means all rows
# (3,2) -> first return 3rd column and then 2nd column

array([[23,  1],
       [33, 21],
       [ 7, 24]])

In [44]:
sample_matrix[0:2,2]

array([ 1, 21])

In [43]:
sample_array = np.arange(1,20)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [45]:
sample_array + sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [46]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [47]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [48]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [49]:
np.max(sample_array)

19

In [50]:
np.min(sample_array)

1

In [51]:
np.argmax(sample_array)

18

In [52]:
np.argmin(sample_array)

0

In [53]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361], dtype=int32)

In [54]:
np.std(sample_array)

5.477225575051661

In [55]:
np.var(sample_array)

30.0

In [56]:
np.mean(sample_array)

10.0

In [57]:
array = np.random.randn(3,4)
array

array([[-1.49541059,  1.24675899, -1.05255511,  1.46584107],
       [ 0.1462048 ,  0.38170202, -1.29293479, -0.24305483],
       [-0.92745188,  0.56238676,  1.09666854,  0.96196783]])

In [58]:
np.round(array,decimals=3)

array([[-1.495,  1.247, -1.053,  1.466],
       [ 0.146,  0.382, -1.293, -0.243],
       [-0.927,  0.562,  1.097,  0.962]])

In [60]:
sports = np.array(['golf','cricket','foot ball','basketball','foot ball','cricket'])
np.unique(sports)

array(['basketball', 'cricket', 'foot ball', 'golf'], dtype='<U10')

In [ ]:
### U10 implies Unicode and 10 characters ie., the array contains words with a maximum characters length of 10.

# Pandas : To create data, table, manipulation

In [63]:
import pandas as pd

In [64]:
df = pd.read_csv("CardioGoodFitness.csv")

In [65]:
df.head()

Product  Age  Gender  Education MaritalStatus  Usage  Fitness  Income  Miles
0   TM195   18    Male         14        Single      3        4   29562    112
1   TM195   19    Male         15        Single      2        3   31836     75
2   TM195   19  Female         14     Partnered      4        3   30699     66
3   TM195   19    Male         12        Single      3        3   32973     85
4   TM195   20    Male         13     Partnered      4        2   35247     47

In [66]:
df.tail()

Product  Age Gender  Education MaritalStatus  Usage  Fitness  Income  \
175   TM798   40   Male         21        Single      6        5   83416   
176   TM798   42   Male         18        Single      5        4   89641   
177   TM798   45   Male         16        Single      5        5   90886   
178   TM798   47   Male         18     Partnered      4        5  104581   
179   TM798   48   Male         18     Partnered      4        5   95508   

     Miles  
175    200  
176    200  
177    160  
178    120  
179    180

In [70]:
df.sample() # random row

Product  Age Gender  Education MaritalStatus  Usage  Fitness  Income  \
178   TM798   47   Male         18     Partnered      4        5  104581   

     Miles  
178    120

In [74]:
df.sample(10) # 10 random rows

Product  Age  Gender  Education MaritalStatus  Usage  Fitness  Income  \
127   TM498   34    Male         15        Single      3        3   67083   
38    TM195   26  Female         16        Single      3        3   36384   
57    TM195   32  Female         14        Single      3        4   46617   
120   TM498   33    Male         13     Partnered      4        4   53439   
85    TM498   21    Male         16     Partnered      2        2   34110   
48    TM195   28    Male         14        Single      4        3   54576   
10    TM195   22    Male         14        Single      3        3   36384   
112   TM498   29  Female         14     Partnered      3        3   51165   
78    TM195   47    Male         16     Partnered      4        3   56850   
158   TM798   26    Male         16     Partnered      5        4   64741   

     Miles  
127     85  
38      66  
57     113  
120    170  
85      42  
48     113  
10      85  
112     95  
78      94  
158    180

In [75]:
df.info() # nummber of rows without missing values datatype

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   Product        180 non-null    object
 1   Age            180 non-null    int64 
 2   Gender         180 non-null    object
 3   Education      180 non-null    int64 
 4   MaritalStatus  180 non-null    object
 5   Usage          180 non-null    int64 
 6   Fitness        180 non-null    int64 
 7   Income         180 non-null    int64 
 8   Miles          180 non-null    int64 
dtypes: int64(6), object(3)
memory usage: 12.8+ KB


In [76]:
df.shape

(180, 9)

In [77]:
df.dtypes

Product          object
Age               int64
Gender           object
Education         int64
MaritalStatus    object
Usage             int64
Fitness           int64
Income            int64
Miles             int64
dtype: object

In [78]:
df.isnull()

Product    Age  Gender  Education  MaritalStatus  Usage  Fitness  Income  \
0      False  False   False      False          False  False    False   False   
1      False  False   False      False          False  False    False   False   
2      False  False   False      False          False  False    False   False   
3      False  False   False      False          False  False    False   False   
4      False  False   False      False          False  False    False   False   
..       ...    ...     ...        ...            ...    ...      ...     ...   
175    False  False   False      False          False  False    False   False   
176    False  False   False      False          False  False    False   False   
177    False  False   False      False          False  False    False   False   
178    False  False   False      False          False  False    False   False   
179    False  False   False      False          False  False    False   False   

     Miles  
0    False  
1    False  
2    False  
3    False  
4    False  
..     ...  
175  False  
176  False  
177  False  
178  False  
179  False  

[180 rows x 9 columns]

In [79]:
df.isnull().sum()

Product          0
Age              0
Gender           0
Education        0
MaritalStatus    0
Usage            0
Fitness          0
Income           0
Miles            0
dtype: int64

In [80]:
df.describe()

Age   Education       Usage     Fitness         Income  \
count  180.000000  180.000000  180.000000  180.000000     180.000000   
mean    28.788889   15.572222    3.455556    3.311111   53719.577778   
std      6.943498    1.617055    1.084797    0.958869   16506.684226   
min     18.000000   12.000000    2.000000    1.000000   29562.000000   
25%     24.000000   14.000000    3.000000    3.000000   44058.750000   
50%     26.000000   16.000000    3.000000    3.000000   50596.500000   
75%     33.000000   16.000000    4.000000    4.000000   58668.000000   
max     50.000000   21.000000    7.000000    5.000000  104581.000000   

            Miles  
count  180.000000  
mean   103.194444  
std     51.863605  
min     21.000000  
25%     66.000000  
50%     94.000000  
75%    114.750000  
max    360.000000

In [81]:
df.describe(include='all')

Product         Age Gender   Education MaritalStatus       Usage  \
count      180  180.000000    180  180.000000           180  180.000000   
unique       3         NaN      2         NaN             2         NaN   
top      TM195         NaN   Male         NaN     Partnered         NaN   
freq        80         NaN    104         NaN           107         NaN   
mean       NaN   28.788889    NaN   15.572222           NaN    3.455556   
std        NaN    6.943498    NaN    1.617055           NaN    1.084797   
min        NaN   18.000000    NaN   12.000000           NaN    2.000000   
25%        NaN   24.000000    NaN   14.000000           NaN    3.000000   
50%        NaN   26.000000    NaN   16.000000           NaN    3.000000   
75%        NaN   33.000000    NaN   16.000000           NaN    4.000000   
max        NaN   50.000000    NaN   21.000000           NaN    7.000000   

           Fitness         Income       Miles  
count   180.000000     180.000000  180.000000  
unique         NaN            NaN         NaN  
top            NaN            NaN         NaN  
freq           NaN            NaN         NaN  
mean      3.311111   53719.577778  103.194444  
std       0.958869   16506.684226   51.863605  
min       1.000000   29562.000000   21.000000  
25%       3.000000   44058.750000   66.000000  
50%       3.000000   50596.500000   94.000000  
75%       4.000000   58668.000000  114.750000  
max       5.000000  104581.000000  360.000000

In [82]:
import pandas as pd
import numpy as np

In [83]:
labels = ['w','x','y','z']
sample_list = [100,200,300,400]
array = np.array([1,2,3,4])
dict = {'w':10,'x':20,'y':30,'z':40}

In [ ]:
# pd.Series - used for one-dimesional data
# pd.DataFrame - used for teo-dimensional data

In [85]:
pd.Series(data=array)

0    1
1    2
2    3
3    4
dtype: int32

In [86]:
pd.Series(data=sample_list,index=labels)

w    100
x    200
y    300
z    400
dtype: int64

In [87]:
pd.Series(sample_list,array)

1    100
2    200
3    300
4    400
dtype: int64

In [88]:
pd.Series(dict)

w    10
x    20
y    30
z    40
dtype: int64